title: "Xingkai Fang"
email: your@email.com
description: "Biomedical Engineering | Medical Imaging"
url: "https://fangxk2003.github.io"
baseurl: ""  # for GitHub Pages, keep it blank
repository: "fangxk2003/fangxk2003.github.io"

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name: "Xingkai Fang"
  avatar: "/assets/images/profile.jpg"
  bio: "Junior | Medical Imaging | SJTU"
